version: '3.1'

services:
  backend-php-cli:
    build: ./docker/php-cli
    volumes:
      - .:/var/www/html
      
  backend-php-fpm:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  backend-nginx:
    image: nginx:latest
    ports:
      - 8099:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  backend-db:
    image: mariadb:10.6
    restart: always
    ports:
      - 33099:3306
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ~/ecosystem/lib_mysql/backend-db/:/var/lib/mysql

  backend-composer:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: composer update